trigger:
- main  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    containerRegistry: '<YourServiceConnection>'
    repository: '<YourDockerHubRepo>'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
